package com.appcoins.sdk.billing.utils

object AppcoinsBillingConstants {
    const val KEY_BUY_INTENT = "BUY_INTENT"
    const val KEY_BUY_INTENT_RAW = "BUY_INTENT_RAW"

    const val RESPONSE_CODE = "RESPONSE_CODE"

    const val INAPP_PURCHASE_ID_LIST = "INAPP_PURCHASE_ID_LIST"
    const val INAPP_PURCHASE_ID = "INAPP_PURCHASE_ID"
    const val INAPP_PURCHASE_ITEM_LIST = "INAPP_PURCHASE_ITEM_LIST"
    const val INAPP_PURCHASE_DATA_LIST = "INAPP_PURCHASE_DATA_LIST"
    const val INAPP_PURCHASE_DATA = "INAPP_PURCHASE_DATA"

    const val INAPP_DATA_SIGNATURE_LIST = "INAPP_DATA_SIGNATURE_LIST"
    const val INAPP_DATA_SIGNATURE = "INAPP_DATA_SIGNATURE"

    const val INAPP_VOIDED_PURCHASE_DATA_LIST = "INAPP_VOIDED_PURCHASE_DATA_LIST"

    const val ORDER_REFERENCE = "order_reference"
    const val SKU_TYPE = "SKU_TYPE"

    const val GET_SKU_DETAILS_ITEM_LIST = "ITEM_ID_LIST"

    const val RESULT_CODE = 51

    const val TIMEOUT_3_SECS = 3000
    const val TIMEOUT_30_SECS = 30000
}
