package com.appcoins.sdk.billing.utils

object AppcoinsBillingConstants {
    const val RESPONSE_CODE = "RESPONSE_CODE"

    const val INAPP_PURCHASE_ID_LIST = "INAPP_PURCHASE_ID_LIST"
    const val INAPP_PURCHASE_ID = "INAPP_PURCHASE_ID"
    const val INAPP_PURCHASE_ITEM_LIST = "INAPP_PURCHASE_ITEM_LIST"
    const val INAPP_PURCHASE_DATA_LIST = "INAPP_PURCHASE_DATA_LIST"
    const val INAPP_PURCHASE_DATA = "INAPP_PURCHASE_DATA"

    const val INAPP_DATA_SIGNATURE_LIST = "INAPP_DATA_SIGNATURE_LIST"
    const val INAPP_DATA_SIGNATURE = "INAPP_DATA_SIGNATURE"

    const val ORDER_REFERENCE = "order_reference"

    const val GET_SKU_DETAILS_ITEM_LIST = "ITEM_ID_LIST"
}
