#!/bin/sh

echo "Running Codestyle verifications (Checkstyle, Lint & Detekt) on pre-push..."
echo "Current directory: $(pwd)"
if ! make check; then
    echo "Code style checks failed. Push aborted."
    exit 1
fi

exit 0
